### ISSUE TITLE
Error: make 

### ISSUE THREAD

**Issue by Batmanabcdefg** [tjhei/paper-parallel-gmg-data#1]
/home/user/paper-parallel-gmg-data/elasticity-dg/step-39.cc:774:37: error: cannot declare variable ‘ellipse1’ to be of abstract type ‘Step39::EllipseManifold<3>’
         static EllipseManifold<dim> ellipse1(s2+s3, 2., std::sqrt(8));
                                     ^~~~~~~~

**Comment by tjhei** [comment]
thanks, will post a fix in a minute.

**Comment by Batmanabcdefg** [comment]
@tjhei , Thanks a lot for your support!

Kind regards!

**Comment by tjhei** [comment]
The code now compiles but the 3 cylinder problem has a runtime error regarding the manifold description. I am not sure what changed between when we created the example and the current deal.II version. I will report back and fix it.

**Comment by tjhei** [comment]
things are working correctly, as far as I can tell.
